name: Manual Publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version number for this release. Must be SemVer compliant.'
        required: true
      dry_run:
        type: boolean
        description: 'Run build without deploying'
        required: false
        default: false
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: central
        steps:
            - uses: actions/checkout@v4
            - name: Set up Maven Central Repository
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  server-id: central
                  server-username: MAVEN_USERNAME
                  server-password: MAVEN_PASSWORD
                  gpg-private-key: ${{ secrets.GPG_KEY }}
                  gpg-passphrase: MAVEN_GPG_PASSPHRASE
            - name: Set version
              run: mvn versions:set -DnewVersion=${{ github.event.release.tag_name }}
            - name: Publish package
              run: |
                if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
                  echo "Running dry run (no deploy)..."
                  mvn clean verify -P release -Dgpg.skip
                else
                  echo "Deploying to Maven Central..."
                  mvn -P release --batch-mode deploy -DskipTests
                fi
              env:
                MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
                MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
